[package]
name = "demo-2d-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
rusttype = "0.9.2"
fontdue = "0.7.2"
once_cell = "1.9.0"
fast_image_resize = "0.3.1"
